version: "2"

linters:
  enable:
    - govet
    - goconst
    - gocyclo
    - misspell
    - unconvert
    - prealloc
    - gocritic
    - revive
    - staticcheck
    - unused
    - whitespace
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - gosec
          - dupl

formatters:
  enable:
    - gofmt
    - goimports
