linters:
  disable:
    - exportloopref
  enable:
    - gofmt
    - govet
    - gosimple
    - goconst
    - gocyclo
    - goimports
    - misspell
    - unconvert
    - prealloc
    - gocritic
    - revive
    - staticcheck
    - stylecheck
    - unused
    - whitespace

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
        - dupl

run:
  tests: true
